version: '3.8'
services:
    nestjs:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: jmart-backend
        ports:
            - 3000:3000
        networks:
            - default
        volumes:
            - backend:/usr/src/backend/static

volumes:
    backend:

networks:
    default:
        driver: bridge
